version: "3.9"
services:
  rabitmq3:
    container_name: rabitmq3
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
  
  postgres:
    container_name: postgres
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5400:5400"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  
  webapp:
    container_name: webApp
    build:
      context: .
      dockerfile: WebApp.Mvc/Dockerfile
    ports:
      - "1234:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development