version: "3.9"
services:
  rabitmq3:
    container_name: rabitmq3
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
  webapp:
    container_name: webApp
    build:
      context: .
      dockerfile: WebApp.Mvc/Dockerfile
    ports:
      - "80:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development